version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./TodoServer
    container_name: todo-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_list_db

  frontend:
    build: ./Todo_frontend
    container_name: todo-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
